rows = 100
cols = 100
usingPBC = true
reconnectionMethod = none
experiment = reversibilityProtocolTest
nrThreads = 3
seed = 0
QDSD = 0.0
initialGuessNoise = 0.0
meshDiagonal = major
startLoad = 0.138
loadIncrement = 1e-5
maxLoad = 0.1561
GP1 = 0.0
GP2 = 0.0
GP3 = 0.0
minimizer = LBFGS
epsR = 1e-20
LBFGSNrCorrections = 3
LBFGSScale = 1.0
LBFGSEpsg = 1e-5
LBFGSEpsf = 0.0
LBFGSEpsx = 0.0
LBFGSMaxIterations = 0
CGEpsg = 1e-15
CGEpsf = 0.0
CGEpsx = 0.0
CGMaxIterations = 0
finc = 1.1
fdec = 0.5
alphaStart = 0.1
falpha = 0.99
dtStart = 0.01
dtMax = 0.03
dtMin = 1e-12
maxCompS = 0.01
eps = 1e-15
epsRel = 0.0
delta = 0.0
maxIt = 200000
logDuringMinimization = false
fullMinimizationLogging = false
writeDebugVTUs = false
writeDumps = false
writeMeshVTUs = false
dumpPreEventAfterReversibility = true
saveElasticReversibilityStates = false
maximumSavedElasticReversibilityStates = 0
nrVTUFrames = 1
plasticityEventThreshold = 0.05
energyDropThreshold = 0.0001
showProgress = -1
name = common_event_collector_100x100
