"""Show all eight discrete decompositions generated by m1 and m2."""

from __future__ import annotations

from collections import deque

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from MTMath.reduction import elastic_domain_quadrant
from Plotting.matrix_visualization import draw_matrix_columns
from Plotting.plasticReductionCorrectnessIllustration import (
    COLUMN_COLORS,
    GRID,
    KNOWN_PLASTIC_F,
    M1,
    M2,
    OUT,
    PLOT_LIMIT,
    TEXT,
    TOTAL_F,
    apply_style,
)


OUTPUT_STEM = OUT / "plastic_reduction_all_decompositions_illustration"
GENERATORS = ((1, M1), (2, M2))

# Dihedral normal form: r = m1 m2 is a quarter-turn and s = m1 is a reflection.
# The top row is M r^k; the bottom row is M r^k s.
TABLE_WORDS = (
    (),
    (1, 2),
    (1, 2, 1, 2),
    (2, 1),
    (1,),
    (1, 2, 1),
    (2, 1, 2),
    (2,),
)
TABLE_EXPRESSIONS = (
    r"$\mathbf{M}$",
    r"$\mathbf{M}\mathbf{r}$",
    r"$\mathbf{M}\mathbf{r}^{2}$",
    r"$\mathbf{M}\mathbf{r}^{3}$",
    r"$\mathbf{M}\mathbf{s}$",
    r"$\mathbf{M}\mathbf{r}\mathbf{s}$",
    r"$\mathbf{M}\mathbf{r}^{2}\mathbf{s}$",
    r"$\mathbf{M}\mathbf{r}^{3}\mathbf{s}$",
)


def _matrix_key(matrix):
    return tuple(np.rint(matrix).astype(int).ravel())


def generated_symmetry_group():
    """Return the eight unique matrices generated by right-multiplying m1/m2."""
    queue = deque([((), np.eye(2))])
    group = {}
    while queue:
        word, matrix = queue.popleft()
        key = _matrix_key(matrix)
        if key in group:
            continue
        group[key] = {"word": word, "symmetry": matrix}
        for generator_index, generator in GENERATORS:
            queue.append((word + (generator_index,), matrix @ generator))

    if len(group) != 8:
        raise RuntimeError(f"Expected 8 generated symmetries, got {len(group)}")
    return tuple(group.values())


def _symmetry_from_word(word):
    symmetry = np.eye(2)
    for generator_index in word:
        symmetry = symmetry @ (M1 if generator_index == 1 else M2)
    return symmetry


def decomposition_table_data():
    """Return the eight unique M transforms and their factor pairs."""
    generated = generated_symmetry_group()
    generated_keys = {_matrix_key(item["symmetry"]) for item in generated}
    table_keys = {_matrix_key(_symmetry_from_word(word)) for word in TABLE_WORDS}
    if table_keys != generated_keys or len(table_keys) != len(TABLE_WORDS):
        raise RuntimeError("TABLE_WORDS must contain each generated symmetry once")

    base_M = np.linalg.inv(KNOWN_PLASTIC_F)
    decompositions = []
    for word in TABLE_WORDS:
        symmetry = _symmetry_from_word(word)
        reduction_M = base_M @ symmetry
        F_e = TOTAL_F @ reduction_M
        F_p = np.linalg.inv(reduction_M)
        determinant = int(round(np.linalg.det(reduction_M)))
        if determinant not in (-1, 1):
            raise RuntimeError(f"Expected a unimodular M, got det(M)={determinant}")
        decompositions.append(
            {
                "word": word,
                "expression": TABLE_EXPRESSIONS[len(decompositions)],
                "symmetry": symmetry,
                "M": reduction_M,
                "F_e": F_e,
                "F_p": F_p,
                "determinant": determinant,
                "quadrant": int(elastic_domain_quadrant(F_e.T @ F_e)),
            }
        )
    return decompositions


def _draw_factor(ax, matrix, label):
    draw_matrix_columns(
        ax,
        matrix,
        limits=(-PLOT_LIMIT, PLOT_LIMIT),
        colors=COLUMN_COLORS,
        linestyles=("-", "-"),
        linewidth=2.15,
        mutation_scale=11,
        grid_color=GRID,
        origin_color=TEXT,
        show_ticks=False,
    )
    ax.axhline(0.0, color=GRID, linewidth=0.5, zorder=0)
    ax.axvline(0.0, color=GRID, linewidth=0.5, zorder=0)
    ax.text(
        0.06,
        0.93,
        label,
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=9.5,
        color=TEXT,
        bbox={"facecolor": "white", "edgecolor": "none", "pad": 0.8},
        zorder=6,
    )


def make_figure(data=None):
    """Create a 2x4 table with side-by-side elastic and plastic factors."""
    if data is None:
        data = decomposition_table_data()

    fig = plt.figure(figsize=(15.2, 5.2))
    outer = fig.add_gridspec(
        2,
        4,
        left=0.025,
        right=0.99,
        bottom=0.055,
        top=0.88,
        wspace=0.15,
        hspace=0.20,
    )

    titles = []
    for index, decomposition in enumerate(data):
        row, column = divmod(index, 4)
        pair = outer[row, column].subgridspec(1, 2, wspace=0.045)
        elastic_ax = fig.add_subplot(pair[0, 0])
        plastic_ax = fig.add_subplot(pair[0, 1])
        _draw_factor(elastic_ax, decomposition["F_e"], r"$\mathbf{F}_e$")
        _draw_factor(plastic_ax, decomposition["F_p"], r"$\mathbf{F}_p$")

        titles.append((elastic_ax, plastic_ax, decomposition["expression"]))

    fig.canvas.draw()
    fig.text(
        0.5,
        0.965,
        r"$\mathbf{r}=\mathbf{m}_1\mathbf{m}_2,\quad \mathbf{s}=\mathbf{m}_1$",
        ha="center",
        va="top",
        fontsize=11.0,
        color=TEXT,
    )
    for row_index, row_label in enumerate(
        (
            r"rotation coset: $\mathbf{M}\mathbf{r}^{k}$",
            r"reflection coset: $\mathbf{M}\mathbf{r}^{k}\mathbf{s}$",
        )
    ):
        row_axes = [ax_pair[0] for ax_pair in titles[row_index * 4 : (row_index + 1) * 4]]
        y = sum(ax.get_position().y0 + ax.get_position().height / 2 for ax in row_axes) / len(row_axes)
        fig.text(
            0.009,
            y,
            row_label,
            ha="left",
            va="center",
            rotation=90,
            fontsize=8.8,
            color=TEXT,
        )
    for elastic_ax, plastic_ax, expression in titles:
        elastic_box = elastic_ax.get_position()
        plastic_box = plastic_ax.get_position()
        fig.text(
            (elastic_box.x0 + plastic_box.x1) / 2,
            max(elastic_box.y1, plastic_box.y1) + 0.012,
            expression,
            ha="center",
            va="bottom",
            fontsize=10.2,
            color=TEXT,
        )
    return fig


def main():
    apply_style()
    data = decomposition_table_data()
    fig = make_figure(data)
    OUT.mkdir(parents=True, exist_ok=True)
    png_path = OUTPUT_STEM.with_suffix(".png")
    pdf_path = OUTPUT_STEM.with_suffix(".pdf")
    fig.savefig(png_path, dpi=240, bbox_inches="tight", facecolor="white")
    fig.savefig(pdf_path, facecolor="white")
    plt.close(fig)
    print(f"generated {len(data)} unique decompositions")
    print(png_path)
    print(pdf_path)
    return png_path, pdf_path


if __name__ == "__main__":
    main()
