"""Generate individual and multi-page plots for several energy drops.

The default command creates drops 1--20, ranked from largest to smallest,
from the first 250x250 non-reconnecting seed.  Drop 100 is excluded because
it is the single-drop example already generated by
``Plotting.plot_single_energy_drop``.

Run from the repository root with::

    MPLCONFIGDIR=/tmp/mpl-cache .venv/bin/python -m \
        Plotting.plot_many_energy_drops
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
from matplotlib import pyplot as plt
from PIL import Image

from Plotting.plot_single_energy_drop import (
    DEFAULT_CSV,
    load_drop_trace,
    plot_drop_trace,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "Plots/single_energy_drop/other_drops"
DEFAULT_PDF = PROJECT_ROOT / "Plots/single_energy_drop/other_20_energy_drops.pdf"


def _drop_numbers(
    *, start: int, count: int, exclude: int | None
) -> list[int]:
    if start < 1:
        raise ValueError("start must be at least 1.")
    if count < 1:
        raise ValueError("count must be at least 1.")
    if exclude is not None and exclude < 1:
        raise ValueError("exclude must be at least 1 or omitted.")

    numbers = []
    candidate = start
    while len(numbers) < count:
        if candidate != exclude:
            numbers.append(candidate)
        candidate += 1
    return numbers


def _combine_pngs_into_pdf(image_paths: list[Path], pdf_path: Path) -> None:
    """Place each finished PNG on a separate PDF page without recropping it."""

    if not image_paths:
        raise ValueError("Cannot create a PDF without image pages.")

    pages = []
    for image_path in image_paths:
        with Image.open(image_path) as image:
            pages.append(image.convert("RGB"))
    first_page, *remaining_pages = pages
    first_page.save(
        pdf_path,
        "PDF",
        save_all=True,
        append_images=remaining_pages,
        resolution=220.0,
    )
    for page in pages:
        page.close()


def generate_plots(
    csv_path: str | Path = DEFAULT_CSV,
    *,
    start: int = 1,
    count: int = 20,
    exclude: int | None = 100,
    drop_order: str = "largest",
    drop_measure: str = "S",
    pre_steps: int = 10,
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    pdf_path: str | Path = DEFAULT_PDF,
    ylim_margin: float = 0.08,
) -> list[Path]:
    """Write one PNG per drop and collect the same figures into a PDF."""

    numbers = _drop_numbers(start=start, count=count, exclude=exclude)
    output_dir = Path(output_dir).expanduser()
    pdf_path = Path(pdf_path).expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)
    pdf_path.parent.mkdir(parents=True, exist_ok=True)

    image_paths = []
    for number in numbers:
        trace = load_drop_trace(
            csv_path,
            pre_steps=pre_steps,
            drop_number=number,
            drop_order=drop_order,
            drop_measure=drop_measure,
        )
        image_path = output_dir / f"drop_{number:03d}.png"
        fig, _, _ = plot_drop_trace(
            trace,
            output_path=image_path,
            ylim_margin=ylim_margin,
        )
        plt.close(fig)
        image_paths.append(image_path)

    _combine_pngs_into_pdf(image_paths, pdf_path)

    print(f"Wrote {len(image_paths)} individual plots to {output_dir.resolve()}")
    print(f"Wrote multi-page PDF to {pdf_path.resolve()}")
    return image_paths


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    parser.add_argument(
        "--start-drop-number",
        type=int,
        default=1,
        help="First one-based drop number (default: 1).",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=20,
        help="Number of plots to create (default: 20).",
    )
    parser.add_argument(
        "--exclude-drop-number",
        type=int,
        default=100,
        help="Drop number to skip; use 0 to exclude none (default: 100).",
    )
    parser.add_argument(
        "--drop-order",
        choices=("largest", "chronological"),
        default="largest",
        help="Ordering used by drop numbers (default: largest).",
    )
    parser.add_argument("--drop-measure", choices=("S", "R"), default="S")
    parser.add_argument("--pre-steps", type=int, default=10)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--pdf", type=Path, default=DEFAULT_PDF)
    parser.add_argument("--ylim-margin", type=float, default=0.08)
    return parser


def main(argv: list[str] | None = None) -> None:
    args = _build_parser().parse_args(argv)
    exclude = None if args.exclude_drop_number == 0 else args.exclude_drop_number
    generate_plots(
        args.csv,
        start=args.start_drop_number,
        count=args.count,
        exclude=exclude,
        drop_order=args.drop_order,
        drop_measure=args.drop_measure,
        pre_steps=args.pre_steps,
        output_dir=args.output_dir,
        pdf_path=args.pdf,
        ylim_margin=args.ylim_margin,
    )


if __name__ == "__main__":
    main()
